[package]
name = "zkevm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2-snark-aggregator-circuit = { path = "../../halo2-snark-aggregator/halo2-snark-aggregator-circuit" }
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256",tag = "v0.1.1" }
halo2_proofs = { path = "../../halo2/halo2_proofs" }
bus-mapping = { path = "../../zkevm-circuits/bus-mapping" }
eth-types = { path = "../../zkevm-circuits/eth-types" }
zkevm-circuits = { path = "../../zkevm-circuits/zkevm-circuits", features = ["test"] }
rand = "0.8"
rand_xorshift = "0.3"
is-even = "1.0.0"
ethers-core = "0.6.0"
hex = "0.4.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.66"
types = { path = "../types", features = ["test"] }
log = "0.4"
anyhow = "1.0"
blake2 = "0.10.3"
dotenv = "0.15.0"
env_logger = "0.9.0"
strum = "0.24"
strum_macros = "0.24"
once_cell = "1.8.0"

[features]
default = ["prove_verify"]
prove_verify = []
