[workspace]
members = [
    "types",
    "zkevm",
    "bin",
]

[profile.test]
opt-level = 3
debug-assertions = true
overflow-checks = false

[profile.release]
opt-level = 3
debug-assertions = true
overflow-checks = false
